/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgv.Telas_Imagens;

import sgv.Telas.*;

/**
 *
 * @author CS INOVAÇÃO
 */
public class MenuPrincipal_Modelo extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal_Modelo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_botao_menu = new javax.swing.JPanel();
        btn_sair = new javax.swing.JButton();
        btn_cliente = new javax.swing.JButton();
        btn_produto = new javax.swing.JButton();
        btn_operacao = new javax.swing.JButton();
        jLabel_foto1 = new javax.swing.JLabel();
        jLabel_foto2 = new javax.swing.JLabel();
        jLabel_foto3 = new javax.swing.JLabel();
        jPanel_mensagem = new javax.swing.JPanel();
        jLabel_mensagem = new javax.swing.JLabel();
        MenuBar_principal = new javax.swing.JMenuBar();
        MenuUsuario = new javax.swing.JMenu();
        jMenu_Fornecedor = new javax.swing.JMenuItem();
        jMenu_Cliente = new javax.swing.JMenuItem();
        jMenu_Produto = new javax.swing.JMenuItem();
        MenuAdministrador = new javax.swing.JMenu();
        jMenu_Funcionario1 = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        jMenu_produtos = new javax.swing.JMenuItem();
        jMenu_fornecedores = new javax.swing.JMenuItem();
        jMenu_vendas = new javax.swing.JMenuItem();
        jMenu_clientes = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        MenuSobreoSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_cliente.setText("Clientes");
        btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clienteActionPerformed(evt);
            }
        });

        btn_produto.setText("Produtos");

        btn_operacao.setText("Operação");
        btn_operacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_botao_menuLayout = new javax.swing.GroupLayout(jPanel_botao_menu);
        jPanel_botao_menu.setLayout(jPanel_botao_menuLayout);
        jPanel_botao_menuLayout.setHorizontalGroup(
            jPanel_botao_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_botao_menuLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_operacao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jPanel_botao_menuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_cliente, btn_operacao, btn_produto, btn_sair});

        jPanel_botao_menuLayout.setVerticalGroup(
            jPanel_botao_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_botao_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_botao_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_operacao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel_botao_menuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_cliente, btn_operacao, btn_produto, btn_sair});

        jLabel_foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel/Telas/imagens/hotel2.jpg"))); // NOI18N

        jLabel_foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel/Telas/imagens/hotel3.jpg"))); // NOI18N

        jLabel_foto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel/Telas/imagens/hotel1.jpg"))); // NOI18N

        jLabel_mensagem.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel_mensagem.setText("Sejam todos bem vindos!");

        javax.swing.GroupLayout jPanel_mensagemLayout = new javax.swing.GroupLayout(jPanel_mensagem);
        jPanel_mensagem.setLayout(jPanel_mensagemLayout);
        jPanel_mensagemLayout.setHorizontalGroup(
            jPanel_mensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mensagemLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel_mensagemLayout.setVerticalGroup(
            jPanel_mensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mensagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
        );

        MenuUsuario.setText("Cadastrar");

        jMenu_Fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_Fornecedor.setText("Cadastrar Fornecedor");
        jMenu_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_FornecedorActionPerformed(evt);
            }
        });
        MenuUsuario.add(jMenu_Fornecedor);

        jMenu_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_Cliente.setText("Cadastrar Cliente");
        MenuUsuario.add(jMenu_Cliente);

        jMenu_Produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_Produto.setText("Cadastrar Produto");
        MenuUsuario.add(jMenu_Produto);

        MenuBar_principal.add(MenuUsuario);

        MenuAdministrador.setText("Administrador");

        jMenu_Funcionario1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenu_Funcionario1.setText("Cadastrar Funcionario");
        MenuAdministrador.add(jMenu_Funcionario1);

        MenuBar_principal.add(MenuAdministrador);

        MenuRelatorio.setText("Relatorio");

        jMenu_produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_produtos.setText("Relatório dos Produtos");
        jMenu_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_produtosActionPerformed(evt);
            }
        });
        MenuRelatorio.add(jMenu_produtos);

        jMenu_fornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_fornecedores.setText("Relatório dos Fornecedores");
        MenuRelatorio.add(jMenu_fornecedores);

        jMenu_vendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_vendas.setText("Relatório dos Vendas");
        MenuRelatorio.add(jMenu_vendas);

        jMenu_clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_clientes.setText("Relatório dos Clientes");
        jMenu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_clientesActionPerformed(evt);
            }
        });
        MenuRelatorio.add(jMenu_clientes);

        MenuBar_principal.add(MenuRelatorio);

        menuAjuda.setText("Ajuda");

        MenuSobreoSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenuSobreoSistema.setText("Sobre o Sistema");
        menuAjuda.add(MenuSobreoSistema);

        MenuBar_principal.add(menuAjuda);

        setJMenuBar(MenuBar_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_foto3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel_botao_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_botao_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_foto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_foto1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_foto3)))
                .addGap(18, 18, 18)
                .addComponent(jPanel_mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
      System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clienteActionPerformed
        new Cliente().setVisible(true);
    }//GEN-LAST:event_btn_clienteActionPerformed

    private void btn_operacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_operacaoActionPerformed

    private void jMenu_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_produtosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_produtosActionPerformed

    private void jMenu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_clientesActionPerformed

    private void jMenu_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_FornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_FornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal_Modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPrincipal_Modelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdministrador;
    private javax.swing.JMenuBar MenuBar_principal;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenuItem MenuSobreoSistema;
    private javax.swing.JMenu MenuUsuario;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_operacao;
    private javax.swing.JButton btn_produto;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel_foto1;
    private javax.swing.JLabel jLabel_foto2;
    private javax.swing.JLabel jLabel_foto3;
    private javax.swing.JLabel jLabel_mensagem;
    private javax.swing.JMenuItem jMenu_Cliente;
    private javax.swing.JMenuItem jMenu_Fornecedor;
    private javax.swing.JMenuItem jMenu_Funcionario1;
    private javax.swing.JMenuItem jMenu_Produto;
    private javax.swing.JMenuItem jMenu_clientes;
    private javax.swing.JMenuItem jMenu_fornecedores;
    private javax.swing.JMenuItem jMenu_produtos;
    private javax.swing.JMenuItem jMenu_vendas;
    private javax.swing.JPanel jPanel_botao_menu;
    private javax.swing.JPanel jPanel_mensagem;
    private javax.swing.JMenu menuAjuda;
    // End of variables declaration//GEN-END:variables
}
