/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgv.Telas;

import sgv.DAO.ClienteDao;
import sgv.Logica.Cliente1;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import sgv.DAO.ProdutoDao;
import sgv.Logica.Produto1;

/**
 *
 * @author CS INOVAÇÃO
 */
public final class Produto extends javax.swing.JFrame {

    //Criando os nomes dos Dados da Tabela...
    DefaultTableModel tmProduto = new DefaultTableModel(null, new String[]{"ID", "Nome", "Valor", "Descrição", "Status", "Quantidade de Estoque"});
    List<Produto1> produtos;//Lista os clientes da Tabela
    ListSelectionModel lsmProduto;//Modelo de seleção da lista de contatos da Tabela

    /**
     * Creates new form Cliente
     */
    public Produto() {
        initComponents();
        desabilitaDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Cliente = new javax.swing.JPanel();
        jText_pesquisar = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        jPanel_DadosCliente = new javax.swing.JPanel();
        jLabel_nome = new javax.swing.JLabel();
        jText_nome = new javax.swing.JTextField();
        jLabel_descricao = new javax.swing.JLabel();
        jTex_descricao = new javax.swing.JTextField();
        jLabel_status = new javax.swing.JLabel();
        jText_Status = new javax.swing.JTextField();
        jLabel_quantidadeEstoque = new javax.swing.JLabel();
        jLabel_valor = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jText_ID = new javax.swing.JTextField();
        btn_imprimir = new javax.swing.JButton();
        jText_valor = new javax.swing.JFormattedTextField();
        jText_quantidadeEstoque = new javax.swing.JFormattedTextField();
        jPanel2_Botoes = new javax.swing.JPanel();
        jBNovo = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBSalvar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_Dados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btn_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgv/Telas_Imagens/pesquisa.png"))); // NOI18N
        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ClienteLayout = new javax.swing.GroupLayout(jPanel_Cliente);
        jPanel_Cliente.setLayout(jPanel_ClienteLayout);
        jPanel_ClienteLayout.setHorizontalGroup(
            jPanel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jText_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_pesquisar)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel_ClienteLayout.setVerticalGroup(
            jPanel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_DadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel_nome.setText("Nome:");

        jText_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_nomeActionPerformed(evt);
            }
        });

        jLabel_descricao.setText("Descrição:");

        jLabel_status.setText("Status:");

        jLabel_quantidadeEstoque.setText("Quantidade Estoque:");

        jLabel_valor.setText("Valor:");

        jLabel_id.setText("Código:");

        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgv/Telas_Imagens/impressora.png"))); // NOI18N
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_DadosClienteLayout = new javax.swing.GroupLayout(jPanel_DadosCliente);
        jPanel_DadosCliente.setLayout(jPanel_DadosClienteLayout);
        jPanel_DadosClienteLayout.setHorizontalGroup(
            jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_DadosClienteLayout.createSequentialGroup()
                        .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nome)
                            .addComponent(jLabel_id))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_DadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel_descricao)
                        .addGap(70, 70, 70)
                        .addComponent(jTex_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_DadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel_quantidadeEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(jText_quantidadeEstoque)))
                .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DadosClienteLayout.createSequentialGroup()
                        .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_imprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_DadosClienteLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel_status)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_Status, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DadosClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_valor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jText_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel_DadosClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTex_descricao, jText_Status, jText_nome, jText_quantidadeEstoque, jText_valor});

        jPanel_DadosClienteLayout.setVerticalGroup(
            jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jText_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_id))
                    .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DadosClienteLayout.createSequentialGroup()
                        .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_nome)
                            .addComponent(jText_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_valor)
                            .addComponent(jText_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_quantidadeEstoque)
                            .addComponent(jText_quantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jText_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_status)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTex_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel_descricao)))
        );

        jPanel_DadosClienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jText_Status, jText_nome});

        jBNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgv/Telas_Imagens/novo.png"))); // NOI18N
        jBNovo.setText("Novo");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jBAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgv/Telas_Imagens/alterar.png"))); // NOI18N
        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgv/Telas_Imagens/excluir.png"))); // NOI18N
        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgv/Telas_Imagens/salvar.png"))); // NOI18N
        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgv/Telas_Imagens/sair1.png"))); // NOI18N
        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2_BotoesLayout = new javax.swing.GroupLayout(jPanel2_Botoes);
        jPanel2_Botoes.setLayout(jPanel2_BotoesLayout);
        jPanel2_BotoesLayout.setHorizontalGroup(
            jPanel2_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2_BotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        jPanel2_BotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBAlterar, jBExcluir, jBNovo, jBSair, jBSalvar});

        jPanel2_BotoesLayout.setVerticalGroup(
            jPanel2_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_BotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBExcluir)
                    .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNovo)
                    .addComponent(jBSalvar)
                    .addComponent(jBSair))
                .addContainerGap())
        );

        jPanel2_BotoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBAlterar, jBExcluir, jBNovo, jBSair, jBSalvar});

        jT_Dados.setModel(tmProduto);
        jT_Dados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmProduto = jT_Dados.getSelectionModel();
        lsmProduto.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e){
                if(! e.getValueIsAdjusting()){
                    jTTabelaLinhaSelecionada(jT_Dados);
                }
            }
        });
        jScrollPane2.setViewportView(jT_Dados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_DadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2_Botoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_DadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2_Botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        dispose(); //saí do modo de execução; 
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed

        habilitaDados();
        jText_nome.setText("");
        jText_valor.setText("");
        jTex_descricao.setText("");
        jText_Status.setText("");
        jText_quantidadeEstoque.setText("");
    }//GEN-LAST:event_jBNovoActionPerformed

    public boolean verificaDados() {

        if (!jText_nome.getText().equals("") && !jTex_descricao.getText().equals("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "O campo nome ou endereço está vazio!");
            return false;
        }
    }

    protected void listarProduto() throws SQLException {

        try {
            ProdutoDao dao = new ProdutoDao();
            produtos = dao.getLista("%" + jText_pesquisar.getText() + "%");
            mostraPesquisa(produtos);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "errro na busca!");
        }
    }

    public void desabilitaDados() {

        jText_ID.setEditable(false);
        jText_nome.setEditable(false);
        jTex_descricao.setEditable(false);
        jText_valor.setEditable(false);
        jText_Status.setEditable(false);
        jText_quantidadeEstoque.setEditable(false);
        
        jText_ID.setText("");
        jText_nome.setText("");
        jTex_descricao.setText("");
        jText_valor.setText("");
        jText_Status.setText("");
        jText_quantidadeEstoque.setText("");

    }

    public void habilitaDados() {
        jText_nome.requestFocus(); //SETAR O FOCO NO CAMPO ESCOLHIDO!
        jText_nome.setEditable(true);
        jTex_descricao.setEditable(true);
        jText_valor.setEditable(true);
        jText_Status.setEditable(true);
        jText_quantidadeEstoque.setEditable(true);
    }

    public void cadastro() throws SQLException {

        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente salvar este produto?",
                "confirmação", JOptionPane.YES_NO_OPTION);

        if (resp == JOptionPane.YES_NO_OPTION) {

            try {
                
                Produto1 produt = new Produto1();
                produt.setNome(jText_nome.getText());
                produt.setValor(jText_valor.getText());
                produt.setDescricao(jTex_descricao.getText());
                produt.setStatus(jText_Status.getText());
                produt.setQuantidadeEstoque(jText_quantidadeEstoque.getText());
                //Chama os dados do banco 
                ProdutoDao dao = new ProdutoDao();
                dao.AdicionaProduto(produt);
                JOptionPane.showMessageDialog(null, "Os dados foram cadastrados com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao realizar o cadastro!");
                JOptionPane.showMessageDialog(null, "Entre em contato com o administrador do sistema!");
            }
            desabilitaDados();
        }
    }

    private void jTTabelaLinhaSelecionada(JTable tabela) {
        if (jT_Dados.getSelectedRow() != -1) {
            habilitaDados();
            jText_ID.setText(String.valueOf(produtos.get(tabela.getSelectedRow()).getIdproduto()));
            jText_nome.setText(produtos.get(tabela.getSelectedRow()).getNome());
            jText_valor.setText(produtos.get(tabela.getSelectedRow()).getValor());
            jTex_descricao.setText(produtos.get(tabela.getSelectedRow()).getDescricao());
            jText_Status.setText(produtos.get(tabela.getSelectedRow()).getStatus());
            jText_quantidadeEstoque.setText(produtos.get(tabela.getSelectedRow()).getQuantidadeEstoque());
            
        } else {

            jText_ID.setText("");
            jText_nome.setText("");
            jTex_descricao.setText("");
            jText_valor.setText("");
            jText_Status.setText("");
            jText_quantidadeEstoque.setText("");

        }
    }


    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:

        if (verificaDados()) {
            try {
                cadastro();
                listarProduto();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao realizar o cadastro!");
            }
            desabilitaDados();
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        try {
            listarProduto();
            desabilitaDados();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao realizar a pesquisa!");
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed

        try {
            alteraProduto();
            listarProduto();
            desabilitaDados();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar produto!");
        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed

        try {
            excluirProduto();
            listarProduto();
            desabilitaDados();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir!");
        }

    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jText_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_nomeActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
        try {
            jT_Dados.print(javax.swing.JTable.PrintMode.FIT_WIDTH,
                new java.text.MessageFormat("Dados dos Produtos"), // titulo da pagina
                new java.text.MessageFormat("Page {0}"));
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this, "Erro ao tentar imprimir!\n"
                + e.getMessage());
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

 /*    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;

            }
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JLabel jLabel_descricao;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_quantidadeEstoque;
    private javax.swing.JLabel jLabel_status;
    private javax.swing.JLabel jLabel_valor;
    private javax.swing.JPanel jPanel2_Botoes;
    private javax.swing.JPanel jPanel_Cliente;
    private javax.swing.JPanel jPanel_DadosCliente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jT_Dados;
    private javax.swing.JTextField jTex_descricao;
    private javax.swing.JTextField jText_ID;
    private javax.swing.JTextField jText_Status;
    private javax.swing.JTextField jText_nome;
    private javax.swing.JTextField jText_pesquisar;
    private javax.swing.JFormattedTextField jText_quantidadeEstoque;
    private javax.swing.JFormattedTextField jText_valor;
    // End of variables declaration//GEN-END:variables

    private void mostraPesquisa(List<Produto1> produtos) {

        while (tmProduto.getRowCount() > 0) {
            tmProduto.removeRow(0);
        }
        if (produtos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum produto cadastrdo no banco de dados!");
        } else {
            String[] linha = new String[]{null, null, null, null, null, null, null};
            for (int i = 0; i < produtos.size(); i++) {
                tmProduto.addRow(linha);
                tmProduto.setValueAt(produtos.get(i).getIdproduto(), i, 0);
                tmProduto.setValueAt(produtos.get(i).getNome(), i, 1);
                tmProduto.setValueAt(produtos.get(i).getDescricao(), i, 2);
                tmProduto.setValueAt(produtos.get(i).getStatus(), i, 3);
                tmProduto.setValueAt(produtos.get(i).getQuantidadeEstoque(), i, 4);
            }
        }
    }

    public void excluirProduto() throws SQLException {

        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este produto?",
                "confirmação", JOptionPane.YES_NO_OPTION);

        if (jT_Dados.getSelectedRow() != -1) {
            if (resp == JOptionPane.YES_NO_OPTION) {
                ProdutoDao dao = new ProdutoDao();
                dao.removeProduto(produtos.get(jT_Dados.getSelectedRow()));
                JOptionPane.showMessageDialog(null, "Produto excluído com Sucesso!");
            }
        }
    }

    private void alteraProduto() throws SQLException {

        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente alterar este produto?",
                "confirmação", JOptionPane.YES_NO_OPTION);

        if (resp == JOptionPane.YES_NO_OPTION) {

            if (jT_Dados.getSelectedRow() != -1) {

                if (verificaDados()) {
                    Produto1 produt = new Produto1();
                    ProdutoDao dao = new ProdutoDao();
                    produt.setIdproduto(Integer.valueOf(jText_ID.getText())); //Altera o Contato pelo ID...
                    produt.setNome(jText_nome.getText());
                    produt.setValor(jText_valor.getText());
                    produt.setDescricao(jTex_descricao.getText());
                    produt.setStatus(jText_Status.getText());
                    produt.setQuantidadeEstoque(jText_quantidadeEstoque.getText());
                    dao.alteraProduto(produt);
                    JOptionPane.showMessageDialog(null, "Produto alterado com sucesso!");
                }
            }
        }
    }
}
