/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgv.Telas;

/**
 *
 * @author Inovação
 */
public class Venda extends javax.swing.JFrame {

    /**
     * Creates new form Operacao
     */
    public Venda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_geral = new javax.swing.JPanel();
        jLabel_vendedor = new javax.swing.JLabel();
        jLabel_tipodevenda = new javax.swing.JLabel();
        jLabel_valorVendido = new javax.swing.JLabel();
        jLabel_valorRecebido = new javax.swing.JLabel();
        jLabel_troco = new javax.swing.JLabel();
        jLabel_mensagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_mensagem1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField_recebido = new javax.swing.JFormattedTextField();
        jFormattedTextField_vendido = new javax.swing.JFormattedTextField();
        jFormattedTextField_troco = new javax.swing.JFormattedTextField();
        jTextField_venda = new javax.swing.JTextField();
        jTextField_Vendedor = new javax.swing.JTextField();
        jButton_Calcular = new javax.swing.JButton();
        jButton_Salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        jLabel_vendedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_vendedor.setText("Vendedor (a):");

        jLabel_tipodevenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_tipodevenda.setText("Tipo de Venda:");

        jLabel_valorVendido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_valorVendido.setText("Valor Vendido:");

        jLabel_valorRecebido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_valorRecebido.setText("Valor Recebido:");

        jLabel_troco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_troco.setText("Troco:");

        jLabel_mensagem.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel_mensagem.setText("SGV SEMPRE COM VOCÊ!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel1.setText("------------------");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("------------------");

        jLabel_mensagem1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel_mensagem1.setText("Caixa de Venda");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setText("--------------------------------");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setText("------------------------");

        jFormattedTextField_recebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jFormattedTextField_vendido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jFormattedTextField_troco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jButton_Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgv/Telas_Imagens/calcular1.png"))); // NOI18N

        jButton_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgv/Telas_Imagens/salvar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1_geralLayout = new javax.swing.GroupLayout(jPanel1_geral);
        jPanel1_geral.setLayout(jPanel1_geralLayout);
        jPanel1_geralLayout.setHorizontalGroup(
            jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_geralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_geralLayout.createSequentialGroup()
                        .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_vendedor)
                            .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1_geralLayout.createSequentialGroup()
                                    .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_valorRecebido)
                                        .addComponent(jLabel_troco))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFormattedTextField_troco, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFormattedTextField_recebido, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1_geralLayout.createSequentialGroup()
                                    .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_valorVendido)
                                        .addComponent(jLabel_tipodevenda))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jFormattedTextField_vendido, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addComponent(jTextField_Vendedor)
                                        .addComponent(jTextField_venda)))
                                .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1_geralLayout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jButton_Salvar))))
                            .addGroup(jPanel1_geralLayout.createSequentialGroup()
                                .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_mensagem1)
                                    .addGroup(jPanel1_geralLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_mensagem)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_geralLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1_geralLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFormattedTextField_recebido, jFormattedTextField_troco, jFormattedTextField_vendido, jTextField_Vendedor, jTextField_venda});

        jPanel1_geralLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_Calcular, jButton_Salvar});

        jPanel1_geralLayout.setVerticalGroup(
            jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_geralLayout.createSequentialGroup()
                .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mensagem1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_vendedor)
                    .addComponent(jTextField_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_geralLayout.createSequentialGroup()
                        .addComponent(jLabel_tipodevenda)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_valorVendido)
                            .addComponent(jFormattedTextField_vendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_valorRecebido)
                            .addComponent(jFormattedTextField_recebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_troco)
                            .addComponent(jFormattedTextField_troco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Salvar)
                    .addComponent(jButton_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1_geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mensagem)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel1_geralLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jFormattedTextField_recebido, jFormattedTextField_troco, jFormattedTextField_vendido, jTextField_Vendedor, jTextField_venda});

        jPanel1_geralLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Calcular, jButton_Salvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1_geral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1_geral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Calcular;
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JFormattedTextField jFormattedTextField_recebido;
    private javax.swing.JFormattedTextField jFormattedTextField_troco;
    private javax.swing.JFormattedTextField jFormattedTextField_vendido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_mensagem;
    private javax.swing.JLabel jLabel_mensagem1;
    private javax.swing.JLabel jLabel_tipodevenda;
    private javax.swing.JLabel jLabel_troco;
    private javax.swing.JLabel jLabel_valorRecebido;
    private javax.swing.JLabel jLabel_valorVendido;
    private javax.swing.JLabel jLabel_vendedor;
    private javax.swing.JPanel jPanel1_geral;
    private javax.swing.JTextField jTextField_Vendedor;
    private javax.swing.JTextField jTextField_venda;
    // End of variables declaration//GEN-END:variables
}
